#!/usr/bin/env python
# vim: syntax=python


PATH_TO_SPADIC_SW = '/home/cbm/cbmflib05/spadic10-sw/spadic'
FLIB_CTRL_BASE_PORT = 9750

import sys
sys.path.insert(0, PATH_TO_SPADIC_SW)
from walter_client import Spadic


def set_neighbors(ctrl, clear=False):
    """
    Set neighbor trigger matrix.

    All odd channels are neighbors and all even channels are neighbors:

      0 2 4 8 10 12 14
      1 3 5 9 11 13 15
    """

    # 1) within channel groups (exclude edge channels)
    for group in 'AB':
        nb = ctrl.digital.neighbor[group]
        nb.reset() # first clear all existings settings
        if clear:
            continue
        for src_ch in range(2, 14):
            for tgt_ch in [src_ch+2, src_ch-2]:
                nb.set(source=src_ch, target=tgt_ch, enable=True)
    if clear:
        return

    # 2) across groups TODO not sure if correct AND working
    pairs = {'A': [(14, 'l0'), (15, 'l1')],
             'B': [(0, 'u0'), (1, 'u1')]}
    for group in 'AB':
        nb = ctrl.digital.neighbor[group]
        for s, t in pairs[group]:
            nb.set(source=s, target=t, enable=True)
            nb.set(source=t, target=s, enable=True)


USAGE = """
usage: spadic_neighbors <syscore #> <spadic #> [clear]

Sets the neighbor trigger matrix, or optionally clears it.
"""

def main(argv):
    try:
        syscore_num, spadic_num = map(int, argv[1:3])
    except:
        raise SystemExit(USAGE)

    try:
        clear = argv[3] == "clear"
    except IndexError:
        clear = False

    port = FLIB_CTRL_BASE_PORT + syscore_num
    host = 'tcp://localhost:%d' % port

    print '%s neighbor matrix of SPADIC #%d at %s...' % (
      ('clearing' if clear else 'setting'), spadic_num, host)
    s = Spadic(host, spadic_num)
    s.ctrl.update()
    set_neighbors(s.ctrl, clear)
    s.ctrl.apply()
    print "OK."

if __name__=='__main__':
    main(sys.argv)
