#!/usr/bin/env python
# vim: syntax=python


PATH_TO_SPADIC_SW = '/home/cbm/cbmflib05/spadic10-sw/spadic'
FLIB_CTRL_BASE_PORT = 9750

import sys
sys.path.insert(0, PATH_TO_SPADIC_SW)
from walter_client import Spadic


#==== the SPADIC configuration =======================================

def set_neighbors(ctrl, channels):
    # neighbor trigger setup
    ctrl.digital.neighbor['A'].set(source=5, target=3, enable=1) # etc

#==== user interface =================================================

USAGE = """
usage: spadic_neighbors <syscore #> <spadic #>
"""

def main(argv):
    try:
        syscore_num, spadic_num = map(int, argv[1:3])
    except:
        raise SystemExit(USAGE)

    port = FLIB_CTRL_BASE_PORT + syscore_num
    host = 'tcp://localhost:%d' % port

    print 'configuring neighbor matrix of SPADIC #%d at %s...' % (spadic_num, host)
    s = Spadic(host, spadic_num)
    set_neighbors(s.ctrl, channels)
    s.ctrl.apply()

if __name__=='__main__':
    main(sys.argv)
