#!/usr/bin/env python
# vim: syntax=python

import struct
import sys
import zmq

ADDR = 0x2F0028
HOST = 'tcp://localhost:{PORT}'
FLIB_BASE_PORT = 9750
LINK_STATUS = {0: "no link", 1: "link active"}

USAGE = """
spadic_link_status <syscore #>
"""

def main(argv):
    try:
        syscore_num = int(argv[1])
    except:
        raise SystemExit(USAGE)

    print 'Reading frontend link status from Syscore #%d...' % syscore_num
    sys.stdout.flush()

    c = zmq.Context()
    s = c.socket(zmq.REQ)
    s.connect(HOST.format(PORT=FLIB_BASE_PORT+syscore_num))

    request = [1, 1, 0x8000, 1, ADDR, 0]
    s.send(struct.pack('<6I', *request))
    _, _, rc, result = struct.unpack('<4I', s.recv())

    if not rc == 1:
        raise SystemExit('Failed to read.')

    for i in range(3):
        print "SPADIC #%d: %s" % (i, LINK_STATUS[(result >> i) & 1])

    print '''
Disclaimer: "%s" may not be accurate.
            Reset the Syscore first to be sure.''' % LINK_STATUS[1]

if __name__=='__main__':
    main(sys.argv)
